OEL-301: OpenEuropa Language Switcher breaks with drupal 9 and oe_theme
openeuropa/oe_multilingual pull request #126
Opened 2021-07-07 15:37 UTC by escuriola

…eme installed.

## OPENEUROPA-301

### Description

[Insert description here]

### Change log

- Added: TrustedCallback class to call from pre_render
- Changed: call to pre_render callback
- Deprecated: 
- Removed: pre_render deprecated method
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-07-12 07:07 UTC, drishu requested changes

2021-07-12 07:07 UTC, drishu commented on src/OpenEuropaLanguageSwitcherBuilder.php
> +class OpenEuropaLanguageSwitcherBuilder implements TrustedCallbackInterface {
No need to prefix the class name we have namespace, lets call it LanguageSwitcherBuilder

2021-07-22 09:42 UTC, ademarco commented
We are moving this pre render in the theme as part of #125.

2021-07-22 10:06 UTC, drishu reviewed
since this code is refactored in https://github.com/openeuropa/oe_multilingual/pull/125 we can close this PR

2021-07-22 10:06 UTC, closed without merging