EWPP-1907: Update to PHP8.
openeuropa/oe_multilingual pull request #130
Opened 2022-01-23 05:27 UTC by 22Alexandra

2022-01-24 11:24 UTC, hernani requested changes
Change also core_version_requirements in modules *.info.yml

2022-01-24 11:35 UTC, hernani submitted a review, later dismissed

2022-01-25 12:56 UTC, yenyasinn approved these changes

2022-01-25 15:22 UTC, hernani approved these changes

2022-01-25 15:24 UTC, merged