EWPP-3861: Support D10.2 and drop D9.
openeuropa/oe_multilingual pull request #152
Opened 2024-01-22 15:40 UTC by nagyad

2024-01-22 17:00 UTC, brummbar requested changes

2024-01-22 17:00 UTC, brummbar commented on .drone.yml
> +    - CORE_VERSION: 10.2
Needs to be 10.2.0 or it will go up.

2024-01-23 08:41 UTC, brummbar submitted a review, later dismissed

2024-01-23 13:16 UTC, drishu requested changes
in tests/modules/translation_importer_test/translation_importer_test.info.yml we can remove ^9.4, no use in holding on to it

2024-01-23 13:50 UTC, brummbar approved these changes

2024-01-23 14:08 UTC, drishu approved these changes

2024-02-02 17:36 UTC, brummbar requested changes

2024-02-02 17:36 UTC, brummbar commented on composer.json
> +        "symfony/phpunit-bridge": "^6.4",
Can't we drop this now?

2024-02-05 14:07 UTC, brummbar approved these changes

2024-02-05 14:15 UTC, merged